### PR TITLE
Fix Type Declarations for ESModule

### LINKED ISSUE #17: Type Declarations not Working for ESModule
When trying to import this package from an ESModule TypeScript ecosystem, it won't work.
TypeScript shows an error stating that the corresponding types could not be found.

This is caused by the `package.json` setting the file for `import` calls to be `index.mjs`.
The setting mentioned before causes TypeScript to go search for the type declarations at `gulp-esbuild/index.d.mts`.

There are basically two ways on how to fix this:
A separate `index.d.mts` file can be created or - if both type declarations match - the types can be set to resolve to `index.d.ts`:

```json
"exports": {
    "types": "./index.d.ts",
    "default": "./index.mjs"
}
```

Sadly, the type declarations do not match (`index.js` uses an export assignment, `index.mjs` uses a default export), so I think a separate type declaration file should be the proper solution.

I'll go create a PR concerning this matter.

### PR DESCRIPTION
**Pull request by neurolag**
Changes made in this PR will add type declarations for the ESModule version of this package.
In doing so, this PR will fix #17.

### CODE REVIEW

**Comment by ym-project** [comment]
Look. We have problems with `index.d.mts` file.
When we use inside mjs file this code snippet:
```js
import gulpEsbuild, {createGulpEsbuild} from "gulp-esbuild";

console.log(gulpEsbuild);
console.log(createGulpEsbuild);
console.log(gulpEsbuild.createGulpEsbuild);

import("gulp-esbuild")
	.then(result => {
		console.log('dynamic import');
		console.log(result.createGulpEsbuild);
		console.log(result.default);
		console.log(result.default.createGulpEsbuild);
	})
```

Typescript uses `index.d.mts` and shows us, what out package has `gulpEsbuild.createGulpEsbuild`. But actually it is not the truth.
```
[Function: plugin]
[Function: createGulpEsbuild]
undefined
dynamic import
[Function: createGulpEsbuild]
[Function: plugin]
undefined
```

Should `mts` declaration file have import from `index.js` file? I think no.

**Comment by ym-project** [comment]
I mean mts declaration file should looks like:
```ts
import {Transform} from 'stream'
import {BuildOptions} from 'esbuild'

type Options = Omit<
	BuildOptions,
	'write' | 'incremental' | 'entryPoints' | 'stdin' | 'watch' | 'allowOverwrite' | 'absWorkingDir' | 'nodePaths'
> & {
	metafileName?: string
}

interface CreateOptions {
	incremental?: boolean
	pipe?: boolean
}

type GulpEsbuild = (options: Options) => Transform
type CreateGulpEsbuild = (options: CreateOptions) => GulpEsbuild

declare const gulpEsbuild: GulpEsbuild;
declare const createGulpEsbuild: CreateGulpEsbuild

export {createGulpEsbuild}
export default gulpEsbuild
```
Without `&` from `d.ts`

**Comment by neurolag** [comment]
Thanks, I totally missed that one
I'll fix it asap

**Comment by neurolag** [comment]
Alright! Fixed it now.
Sorry for the inconvenience

**Pull request merged**
